import fs from 'node:fs';import {locales,routes,defaults,countries} from './src/locales.mjs';
const origin=(process.env.SITE_URL||'https://cleanmargin.dayanand-botla.chatgpt.site').replace(/\/$/,'');
if(!/^https:\/\/[a-z0-9.-]+(?::\d+)?$/i.test(origin))throw Error('SITE_URL must be an HTTPS origin');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fs.mkdirSync('dist/assets',{recursive:true});for(const file of ['style.css','app.mjs','math.mjs'])fs.copyFileSync('src/'+file,'dist/assets/'+file);
fs.writeFileSync('dist/assets/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#113b35"/><path d="M8 21v-6h4v6zm6 0V9h4v12zm6 0v-9h4v9z" fill="#b8ed72"/></svg>');
const urls=[];
for(const [lang,t]of Object.entries(locales))for(const route of routes){
 const index=routes.indexOf(route),tool=index<4,path=`/${lang}/${route}`,title=tool?(index===0?t.title:t.tools[index]+' · '+t.title):({4:t.guideTitle,5:t.about,6:t.privacy,7:t.terms})[index];
 const nav=routes.slice(0,5).map((r,i)=>`<a ${r===route?'aria-current="page"':''} href="/${lang}/${r}">${esc(i<4?t.tools[i]:t.guide)}</a>`).join('');
 const fields=['hours','crew','wage','burden','travel','supplies','overhead','margin','visits',...(index===1?['overrun','discount']:index===2?['discount']:index===3?['actualHours','discount']:[])];
 const form=fields.map(key=>`<label for="${key}">${esc(t[key])}<input id="${key}" name="${key}" type="number" inputmode="decimal" min="${['crew','visits','hours'].includes(key)?1:0}" ${['margin','discount'].includes(key)?'max="99.99"':''} step="${['crew','visits'].includes(key)?1:.01}" value="${defaults[key]}" required></label>`).join('');
 const metric=(label,id,big=false)=>`<div class="metric ${big?'primary':''}"><span>${esc(label)}</span><output id="${id}"></output></div>`;
 const guide=`<section class="article"><div class="section-kicker">CLEANMARGIN / ${esc(t.guide)}</div><h2>${esc(t.guideTitle)}</h2><p class="lede">${esc(t.guideIntro)}</p><ol class="steps">${t.steps.map(([h,p])=>`<li><h3>${esc(h)}</h3><p>${esc(p)}</p></li>`).join('')}</ol></section>`;
 const method=`<section class="article methodology"><h2>${esc(t.method)}</h2><p class="formula">${esc(t.formula)}</p><p>${esc(t.explain)}</p><p>${esc(t.limit)}</p><h3>${esc(t.worked)}</h3><p>${esc(t.workedText)}</p><p class="meta">${esc(t.updated)}</p></section>`;
 const faqs=`<section class="article"><h2>${esc(t.faq)}</h2>${t.faqs.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section>`;
 const settings=`<div class="settings"><label>${esc(t.language)}<select id="language">${Object.entries(locales).map(([l,v])=>`<option value="${l}" ${l===lang?'selected':''}>${v.name}</option>`).join('')}</select></label><label>${esc(t.country)}<select id="country">${Object.entries(countries).map(([c,v])=>`<option value="${c}">${esc(new Intl.DisplayNames([lang],{type:'region'}).of(c))} · ${v}</option>`).join('')}</select></label></div>`;
 const body=tool?`<div class="heading"><div><p class="section-kicker">CLEANMARGIN / ${esc(t.tools[index])}</p><h1>${esc(title)}</h1><p class="lede">${esc(t.intro)}</p></div>${settings}</div><div class="workspace"><section class="input-panel"><div class="panel-head"><h2>${esc(t.inputs)}</h2><span class="badge">${esc(t.status)}</span></div><p class="meta">${esc(t.example)}</p><form id="calculator">${form}</form><p id="error" class="error" role="alert" hidden>${esc(t.error)}</p><p class="currency-note">${esc(t.units)}</p><button type="button" id="reset" class="text-button">${esc(t.reset)}</button></section><aside class="result-panel" aria-label="${esc(t.result)}"><p class="result-kicker">${esc(t.result)}</p>${metric(index===2?t.discounted:t.price,index===2?'discounted':'price',true)}${metric(t.monthly,'monthly')}${metric(t.cost,'cost')}${metric(t.profit,'profit')}${index===1?metric(t.stress,'stressProfit'):index===2?metric(t.profit,'discountProfit'):index===3?metric(t.actual,'actualProfit'):''}${index===1||index===3?metric(t.breakEven,'breakEvenHours'):''}<div class="cost-bar" aria-hidden="true"><div id="cost-fill"></div></div><p class="result-note">${esc(t.local)}</p><button id="print" class="print-button">${esc(t.print)}</button></aside></div><noscript><p>${esc(t.nojs)}</p></noscript>${method}${faqs}`:index===4?`${guide}${method}${faqs}`:`<section class="article legal"><p class="section-kicker">CLEANMARGIN</p><h1>${esc(title)}</h1><p>${esc(index===5?t.aboutText:index===6?t.privacyText:t.termsText)}</p>${index===6?`<button id="preferences" class="text-button">${esc(t.preferences)}</button>`:''}${index===5?`<h2>${esc(t.method)}</h2><p>${esc(t.formula)}</p><p>${esc(t.limit)}</p>`:''}</section>`;
 const data={lang,route,index,t,defaults,countries};const ld={"@context":"https://schema.org","@type":tool?'WebApplication':'WebPage',name:title,url:origin+path,inLanguage:lang,description:tool?t.intro:t.guideIntro,...(tool?{applicationCategory:'BusinessApplication',operatingSystem:'Any',offers:{'@type':'Offer',price:'0',priceCurrency:'EUR'}}:{})};
 const html=`<!doctype html><html lang="${lang}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | CleanMargin</title><meta name="description" content="${esc(tool?t.intro:index===4?t.guideIntro:index===5?t.aboutText:index===6?t.privacyText:t.termsText)}"><link rel="canonical" href="${origin+path}">${Object.keys(locales).map(l=>`<link rel="alternate" hreflang="${l}" href="${origin}/${l}/${route}">`).join('')}<link rel="alternate" hreflang="x-default" href="${origin}/en/${route}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(t.intro)}"><meta property="og:type" content="website"><meta property="og:url" content="${origin+path}"><meta name="theme-color" content="#113b35"><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/assets/style.css"><script type="application/ld+json">${JSON.stringify(ld).replace(/</g,'\\u003c')}</script></head><body><a class="skip" href="#main">${esc(t.links)}</a><header><a class="brand" href="/${lang}/"><img src="/assets/favicon.svg" width="32" height="32" alt=""><span>Clean<span class="brand-light">Margin</span></span></a><span class="tagline">${esc(t.tagline)}</span><a class="header-guide" href="/${lang}/guide/">${esc(t.guide)}</a></header><nav aria-label="${esc(t.links)}">${nav}</nav><main id="main">${body}<section class="related"><h2>${esc(t.links)}</h2><div>${routes.slice(0,5).filter(r=>r!==route).map(r=>{const i=routes.indexOf(r);return `<a href="/${lang}/${r}"><span class="card-num">0${i+1}</span><strong>${esc(i<4?t.tools[i]:t.guide)}</strong></a>`}).join('')}</div></section>${index===4||tool?`<section class="article source"><h2>${esc(t.sources)}</h2><a href="https://www.bdc.ca/en/articles-tools/money-finance/manage-finances/how-calculate-profit-margin">BDC · Profit margin</a></section>`:''}</main><footer><div><strong>CleanMargin</strong><p>${esc(t.footer)}</p></div><div class="footer-links"><a href="/${lang}/about/">${esc(t.about)}</a><a href="/${lang}/privacy/">${esc(t.privacy)}</a><a href="/${lang}/terms/">${esc(t.terms)}</a></div><div class="locale-links">${Object.entries(locales).map(([l,v])=>`<a href="/${l}/${route}" lang="${l}" hreflang="${l}">${v.name}</a>`).join('')}</div></footer><script id="page-data" type="application/json">${JSON.stringify(data).replace(/</g,'\\u003c')}</script><script type="module" src="/assets/app.mjs"></script></body></html>`;
 fs.mkdirSync('dist'+path,{recursive:true});fs.writeFileSync('dist'+path+'index.html',html);urls.push(origin+path);
}
fs.writeFileSync('dist/index.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CleanMargin · Cleaning business tools</title><link rel="canonical" href="${origin}/"><link rel="stylesheet" href="/assets/style.css"><link rel="icon" href="/assets/favicon.svg"></head><body><main class="article"><h1>CleanMargin</h1><p>Commercial cleaning bid and profit tools. Choose your language.</p><div class="locale-links">${Object.entries(locales).map(([l,v])=>`<a href="/${l}/" lang="${l}">${v.name}</a>`).join('')}</div></main></body></html>`);
fs.writeFileSync('dist/404.html','<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Page not found | CleanMargin</title><meta name="robots" content="noindex"><link rel="stylesheet" href="/assets/style.css"></head><body><main class="article"><h1>Page not found</h1><a href="/">CleanMargin</a></main></body></html>');
fs.writeFileSync('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${[origin+'/',...urls].map(u=>`<url><loc>${esc(u)}</loc></url>`).join('')}</urlset>`);
fs.writeFileSync('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
fs.writeFileSync('dist/_headers','/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  X-Frame-Options: SAMEORIGIN\n');
console.log(`Built ${urls.length} localized pages + language selector at ${origin}`);
