import {calculate} from './math.mjs';
const p=JSON.parse(document.getElementById('page-data').textContent);const {lang,route,t,defaults,countries}=p;
const form=document.getElementById('calculator');let country;
const read=()=>{try{return localStorage.getItem('cleanmargin.country')}catch{return null}};
const save=c=>{try{localStorage.setItem('cleanmargin.country',c)}catch{}};
function detect(){for(const l of navigator.languages||[navigator.language]){try{const r=new Intl.Locale(l).region;if(countries[r])return r}catch{}}return {en:'GB',de:'DE',fr:'FR',es:'ES',it:'IT',nl:'NL'}[lang]||'GB'}
country=countries[read()]?read():detect();const selector=document.getElementById('country');if(selector){selector.value=country;selector.addEventListener('change',()=>{country=selector.value;save(country);render()})}
document.getElementById('language')?.addEventListener('change',e=>{location.href=`/${e.target.value}/${route}`});
document.getElementById('preferences')?.addEventListener('click',()=>{try{localStorage.removeItem('cleanmargin.country')}catch{} location.reload()});
const money=n=>new Intl.NumberFormat(lang,{style:'currency',currency:countries[country]}).format(n);
const vread=()=>({...defaults,...Object.fromEntries([...form.querySelectorAll('input')].map(i=>[i.name,i.value.trim()===''?NaN:Number(i.value)]))});
function render(){if(!form)return;const error=document.getElementById('error');let r;try{if(!form.checkValidity())throw Error();r=calculate(vread());error.hidden=true}catch{error.hidden=false;for(const o of document.querySelectorAll('output'))o.textContent='—';return}for(const o of document.querySelectorAll('output')){const value=r[o.id];o.textContent=o.id==='breakEvenHours'?(value===null?'—':new Intl.NumberFormat(lang,{maximumFractionDigits:2}).format(Math.max(0,value))):money(value);o.classList.toggle('negative',typeof value==='number'&&value<0)}document.getElementById('cost-fill').style.width=Math.min(100,r.price>0?r.cost/r.price*100:0)+'%'}
form?.addEventListener('input',render);form?.addEventListener('submit',e=>e.preventDefault());document.getElementById('reset')?.addEventListener('click',()=>{form.reset();render()});document.getElementById('print')?.addEventListener('click',()=>window.print());render();
if(form&&document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_cleaning_quote',description:'Set cleaning quote inputs and update the displayed estimate. Does not send or save a quote.',inputSchema:{type:'object',properties:Object.fromEntries(Object.keys(defaults).map(k=>[k,{type:'number',minimum:0}])),additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!(k in defaults)))throw Error('Invalid inputs');const v={...vread(),...input};const result=calculate(v);for(const [k,n]of Object.entries(input)){const el=form.elements.namedItem(k);if(!el)throw Error('Input is unavailable on this page');if(!Number.isFinite(n))throw Error('Invalid number')}for(const [k,n]of Object.entries(input))form.elements.namedItem(k).value=n;render();return {currency:countries[country],...result}}})).catch(()=>{})}catch{}}
